### PR TITLE
fix: add initialized state to CarouselContext to track carousel initialization

### LINKED ISSUE #78: isSlideActive callback never returns true
The bound DOM updates on the slides themselves don't work. Works for dots e.g. `aria-current="true"` is set properly, just not for the slides themselves.

### PR DESCRIPTION
**Pull request by mi5t4n**
## Summary

This PR updates `aria-current="true"` for the slides as well when it changes.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Enhancement/refactor
- [ ] Documentation update
- [ ] Test update
- [ ] Build/CI/tooling

## Related issue(s)

Closes #78

## What changed

Added an internal flag to check for the Embla initialization before `isSlideActive` callback. 

## Breaking changes

Does this introduce a breaking change? If yes, describe the impact and migration path below.

- [ ] Yes — migration path: 
- [x] No

## Testing

Describe how this was tested.

- [ ] Unit tests
- [x] Manual testing
- [ ] Cross-browser testing (if UI changes)

Test details:

## Screenshots / recordings

If applicable, add screenshots or short recordings.

## Checklist

- [x] I have self-reviewed this PR
- [ ] I have added/updated tests where needed
- [ ] I have updated docs where needed
- [x] I have checked for breaking changes

### CODE REVIEW

**Review by theMasudRana — DISMISSED** [review]
The changes look good to me.

Tested from my end for the following points:

- [x] No breaking changes
- [x] Updates the state correctly when the loop is true.
- [x] Updates the state correctly when free drag is enabled.
- [x] Updates the state correctly when scroll snap is used.

File: src/blocks/carousel/view.ts [hunk 1]
```diff
@@ -95,6 +95,13 @@ store( 'carousel-kit/carousel', {
 	},
 	callbacks: {
 		isSlideActive: () => {
+			// Track initialization state to prevent errors when Embla isn't ready
+			// See: https://github.com/rtCamp/carousel-kit/issues/78
+			const context = getContext<CarouselContext>();
```
Comment (theMasudRana) [inline src/blocks/carousel/view.ts:100]: In the this method, we are calling getContext twice. Since you already define context at the top of the function, you can just use `context.selectedIndex` at the bottom instead of calling the function again.

Comment (mi5t4n) [reply src/blocks/carousel/view.ts:100]: @theMasudRana Nice catch, resolved by https://github.com/rtCamp/carousel-kit/pull/92/changes/ac9f63a8efae20859979a5f729f76b2bb6d47e75

**Review by theMasudRana — APPROVED** [review]
Tested after the last push.
Everything looks good.
